### ISSUE TITLE
Вывод коэффициента Жаккара в тестах

### ISSUE THREAD

**Issue by anton-k** [vonavi/anti-plagiarism#1]
Нужно добавить по ТЗ.

 @vonavi   @voidlizard

**Comment by voidlizard** [comment]
По поводу Жаккара - генерим шинглы (размерность задаём в параметрах) для исходных текстов и для результирующего документа

выводим коэфф. Жаккара для пар

**Comment by vonavi** [comment]
Пока без параметра, задающего размерность, поскольку он жестко задан в функции [genShingle](https://github.com/hexresearch/ap-lsh/blob/master/src/Data/HXR/AP/LSH.hs#L203).
