### ISSUE TITLE
Сделать рандом параметром функции

### ISSUE THREAD

**Issue by anton-k** [vonavi/anti-plagiarism#2]
Было бы хорошо уметь менять зерно рандома. 
В ТЗ нет ,но было бы удобно для тестирования разных случаев.

@vonavi  @voidlizard

**Comment by voidlizard** [comment]
Поддерживаю

**Comment by anton-k** [comment]
Скорее не зерно, а весь генератор. чтобы его можно было с IO внешним кодом получить случайно и передать в функцию плагиата, а дальше всё как в коде чистое.
