### ISSUE TITLE
Программа не справляется с большим корпусом документов

### ISSUE THREAD

**Issue by anton-k** [vonavi/anti-plagiarism#3]
На практике будет ~ 10^6 доков. 

На 1K доков программа работает за 10 сек -- это **медленно**
На 100 K исчерпывает память и зависает.

Нужно решить эту проблему. 

Возможно стоит на начальном этапе рандомно выбрать 20-40 документов из всего корпуса и на них провести алгоритм, который есть сейчас. 

или оставить код как есть, но в тесте предусмотреть, что в папке с файлами их будет очень много и прочитать только небольшую часть их.

@vonavi  @voidlizard

**Comment by voidlizard** [comment]
второе. в тесте отбираем N случайных документов.

**Comment by vonavi** [comment]
Конечно, нужно избавиться от списков, это всегда просадка по скорости и памяти. Планирую их заменить на Vector.Unboxed.
